name: newman using trello collection

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: newman run trello_project.postman_collection.json --global-var "Key=e1410bf3f04b24c0f3f58554034f3c3c" --global-var "Token=ATTA798e3ae06fb2a163adde7d74f017a19a0af06fb6e418112c024a44a66851c9549D41BE77" --global-var "board name=project" --global-var "pos=3527" --global-var "base=https://trello.com"

